config/routes.rb
Rails.application.routes.draw do
  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"

  resources :maps
  resources :calendars
  resources :events
  resources :clubs

  post 'delete_images' => 'clubs#delete_images', as: :delete_images
  get 'home_page/index'
  get 'club_page/index'
  get 'club_page/show'
  get 'club_page/show2'
  get 'club_page/show3'
  get 'calendar/index'
  root 'home_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/club.rb
class Club < ApplicationRecord
    validates :name, :layout, presence: true
    validates :layout, numericality: { only_integer: true}
    has_many_attached :images
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
  end

  def show
    @club = Club.find_by(id: params[:id])
    if (@club.layout == 1)
      render :layout1
    elsif (@club.layout == 2)
      render :layout2
    elsif (@club.layout == 3)
      render :layout3
    else
      render :layout1
    end
  end

  def edit
    @club = Club.find_by(id: params[:id])
  end

  def update
    @club = Club.find_by(id: params[:id])
    if @club.update(club_params)
      if params[:club][:images] != nil
        @club.images.attach(params[:club][:images])
      end
      redirect_to club_path(@club)
    else
      render :edit
    end
  end
  
  def club_params
    params.require(:club).permit(:name, :layout,:title_1,:description_1,
                                 :title_2, :description_2,
                                 :title_3, :description_3,
                                 :title_4, :description_4,
                                 :title_5, :description_5,
                                 :description, :extra_description)
  end

  def delete_images
    @club = Club.find_by(id: params[:id])
    @club.images.each do |image|
      if image
        image.purge
      end
    end
    redirect_to club_path(@club)
  end
  
end

app/helpers/clubs_helper.rb
module ClubsHelper
  def check_if_officer
    if @user.acc_type == "club officer"
      return true
    else
      return false
    end
  end
end

app/views/clubs/edit.html.erb
Edit <%= @club.name %>

<%= form_for @club do |f|  %>
  <%= f.label :name, "Club Name" %>
  <%= f.text_field :name %>

  <%= f.label :layout, "Layout Number" %>
  <%= f.text_field :layout %>

  <%= f.label :title_1, "Section 1 Title" %>
  <%= f.text_field :title_1 %>

  <%= f.label :description_1, "Information Segment 1"%>
  <%= f.text_area :description_1 %>

  <%= f.label :title_2, "Section 2 Title" %>
  <%= f.text_field :title_2 %>
  
  <%= f.label :description_2, "Information Segment 2 " %>
  <%= f.text_area :description_2 %>

  <%= f.label :title_3, "Section 3 Title" %>
  <%= f.text_field :title_3 %>

  <%= f.label :description_3, "Information Segment 3" %>
  <%= f.text_area :description_3 %>

  <%= f.label :title_4, "Section Title 4" %>
  <%= f.text_field :title_4 %>

  <%= f.label :description_4, "Information Segment 4" %>
  <%= f.text_area :description_4 %>

  <%= f.label :title_5, "Section Title 5" %>
  <%= f.text_field :title_5 %>

  <%= f.label :description_5, "Information Segment 5" %>
  <%= f.text_area :description_5 %>


  <%= f.file_field :images, multiple: true %><br>


  <%= f.submit "Save" %>

<% end %>

<br>

<%= button_to 'Delete Images', controller:"clubs", action: "delete_images", id: @club %>

app/views/clubs/index.html.erb
<h1>ClubPage#index</h1>
<p>Find me in app/views/club_page/index.html.erb</p>

app/views/clubs/layout1.html.erb
<style type="text/css" media="all">
  h1 {
    color: rgb(0,0,0);
    font-size: 5em;
    font-weight: bold;
  }

  h2 {
    text-align: left;
    color: rgb(0,0,0);
    font-size: 2em;
    font-weight: bold;
    text-decoration: underline;
  }

  p {
    font-size: 1em;
    color: rgb(0,0,0);
  }
  p.center {
    text-align: center;
  }
  p.right {
    text-align: right;
  }
  p.left {
    text-align: left;
  }

  .column {
    float: left;
    width: 50.00%;
    padding: 15px;
  }
  .row:after {
    content: ""
    display: table;
    clear: both;
</style>

<div id="logo">
  <% if @club.images.first %>
    <%= image_tag @club.images.first %>
  <% end %>
</div>
<br><br>
<div id="club_name">
  <% if @club.name != "" %>
    <h1><%= @club.name %></h1>
  <% end %>
</div>
<br><br>

<% if @club.title_1 != "" %>
  <div id="Section 1">
    <h2><%= @club.title_1 %></h2>
    <p class=left><%= @club.description_1 %></p>
  </div>
<% end %>

<% if @club.title_2 != "" %>
  <div id="Section 2">
    <h2><%= @club.title_2 %></h2>
    <p class=left><%= @club.description_2 %></p>
  </div>
<% end %>

<% if @club.title_3 != "" %>
  <div id="Section 3">
    <h2><%= @club.title_3 %></h2>
    <p class=left><%= @club.description_3 %></p>
  </div>
<% end %>

<% if @club.title_4 != "" %>
  <div id="Section 4">
    <h2><%= @club.title_4 %></h2>
    <p class=left><%= @club.description_4 %></p>
  </div>
<% end %>

<% if @club.title_5 != "" %>
  <div id="Section 5">
    <h2><%= @club.title_5 %></h2>
    <p class=left><%= @club.description_5 %></p>
  </div>
<% end %>

<%= @club.images.offset(1).find_each do |image| %>
  <%= image_tag url_for(image) %>
<% end %>

<div id="edit button">
  <% if current_user && current_user.acc_type == "club officer" %>
    <br>
    <%= button_to "Edit", edit_club_path(@club), :method => :get  %>
  <% end %>

</div>

app/views/clubs/layout2.html.erb
<style type="text/css" media="all">
  h1 {
    color: rgb(0,0,0);
    font-size: 5em;
    font-weight: bold;
  }

  h2 {
    text-align: left;
    color: rgb(0,0,0);
    font-size: 2em;
    font-weight: bold;
    text-decoration: underline;
  }

  p {
    font-size: 1em;
    color: rgb(0,0,0);
  }
  p.center {
    text-align: center;
  }
  p.right {
    text-align: right;
  }
  p.left {
    text-align: left;
  }

  .column {
    float: left;
    width: 50.00%;
    padding: 15px;
  }
  .row:after {
    content: ""
    display: table;
    clear: both;
</style>

<div id="logo">
  <% if @club.images.first %>
    <%= image_tag @club.images.first %>
  <% end %>
</div>
<br><br>
<div id="club_name">
     <h1><%= @club.name %></h1>
</div>
<br><br>
<div class="row">
  <div class="column">
    <% if @club.title_1 != "" %>
      <div id="Section 1">
        <h2><%= @club.title_1 %></h2>
        <p class=left><%= @club.description_1 %></p>
      </div>
    <% end %>

    <% if @club.images.offset(1).first %>
      <%= image_tag url_for(@club.images.offset(1).first) %>
      <br>
    <% end %>

    <% if @club.title_2 != "" %>
      <div id="Section 2">
        <h2><%= @club.title_2 %></h2>
        <p class=left><%= @club.description_2 %></p>
      </div>
    <% end %>

    <% if @club.images.offset(2).first %>
      <%= image_tag url_for(@club.images.offset(2).first) %>
      <br>
    <% end %>

  </div>

  <div class="column">
    <% if @club.title_3 != "" %>
      <div id="Section 3">
        <h2><%= @club.title_3 %></h2>
        <p class=left><%= @club.description_3 %></p>
      </div>
    <% end %>

    <% if @club.images.offset(3).first %>
      <%= image_tag url_for(@club.images.offset(3).first) %>
      <br>
    <% end %>
    
    <% if @club.title_4 != "" %>
      <div id="Section 4">
        <h2><%= @club.title_4 %></h2>
        <p class=left><%= @club.description_4 %></p>
      </div>
    <% end %>

    <% if @club.images.offset(4).first %>
      <%= image_tag url_for(@club.images.offset(4).first) %>
      <br>
    <% end %>

    <% if @club.title_5 != "" %>
      <div id="Section 5">
        <h2><%= @club.title_5 %></h2>
        <p class=left><%= @club.description_5 %></p>
      </div>
    <% end %>

    <% if @club.images.offset(5).first %>
      <%= image_tag url_for(@club.images.offset(5).first) %>
      <br>
    <% end %>
  </div>

</div>


<div id="edit button">
  <% if current_user && current_user.acc_type == "club officer" %>
    <%= button_to "Edit", edit_club_path(@club), :method => :get  %>
  <% end %>

</div>

app/views/clubs/layout3.html.erb
<style type="text/css" media="all">
  h1 {
    color: rgb(0,0,0);
    font-size: 5em;
    font-weight: bold;
  }

  h2 {
    text-align: left;
    color: rgb(0,0,0);
    font-size: 2em;
    font-weight: bold;
    text-decoration: underline;
  }

  p {
    font-size: 1em;
    color: rgb(0,0,0);
  }
  p.center {
    text-align: center;
  }
  p.right {
    text-align: right;
  }
  p.left {
    text-align: left;
  }

  .column {
    float: left;
    width: 50.00%;
    padding: 15px;
  }
  .row:after {
    content: ""
    display: table;
    clear: both;
</style>

<div id="logo">
  <% if @club.images.first %>
    <%= image_tag @club.images.first %>
  <% end %>
</div>
<br><br>
<div id="club_name">
     <h1><%= @club.name %></h1>
</div>
<br><br>
<div class="row">
  <div class="column">
    <% if @club.title_1 != "" %>
      <div id="Section 1">
        <h2><%= @club.title_1 %></h2>
        <p class=left><%= @club.description_1 %></p>
      </div>
    <% end %>

    <% if @club.title_2 != "" %>
      <div id="Section 2">
        <h2><%= @club.title_2 %></h2>
        <p class=left><%= @club.description_2 %></p>
      </div>
    <% end %>

    <% if @club.title_3 != "" %>
      <div id="Section 3">
        <h2><%= @club.title_3 %></h2>
        <p class=left><%= @club.description_3 %></p>
      </div>
    <% end %>
  </div>

  <div class="column">
    <% if @club.images.offset(1).first %>
      <%= image_tag url_for(@club.images.offset(1).first) %>
      <br>
    <% end %>
    
    <% if @club.images.offset(2).first %>
      <%= image_tag url_for(@club.images.offset(2).first) %>
      <br>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="column">
    <% if @club.images.offset(3).first %>
      <%= image_tag url_for(@club.images.offset(3).first) %>
      <br>
    <% end %>
    
    <% if @club.images.offset(4).first %>
      <%= image_tag url_for(@club.images.offset(4).first) %>
      <br>
    <% end %>
  </div>
  <div class = "column">
    <% if @club.title_3 != "" %>
      <div id="Section 3">
        <h2><%= @club.title_3 %></h2>
        <p class=left><%= @club.description_3 %></p>
      </div>
    <% end %>
    <% if @club.title_4 != "" %>
      <div id="Section 4">
        <h2><%= @club.title_4 %></h2>
        <p class=left><%= @club.description_4 %></p>
      </div>
    <% end %>

    <% if @club.title_5 != "" %>
      <div id="Section 5">
        <h2><%= @club.title_5 %></h2>
        <p class=left><%= @club.description_5 %></p>
      </div>
    <% end %>
  </div>

</div>


<div id="edit button">
  <% if current_user && current_user.acc_type == "club officer" %>
    <%= button_to "Edit", edit_club_path(@club), :method => :get  %>
  <% end %>

</div>

app/views/clubs/show.html.erb
<% @club.images.each do |image| %>
  <div class="logo">
    <%= image_tag image %>
  </div>
<% end %>
<div id="club name">
  <h1><%= @club.name %></h1>
</div>
<div id="mission statement">
  <p><%= @club.description %></p>
</div>
<div id="edit button">
  <% if current_user && current_user.acc_type == "club officer" %>
    <%= button_to "Edit",  edit_club_path(@club), :method => :get  %>
  <% end %>

</div>